### ISSUE TITLE
Week 12: Optimization, Frequency, and Recency

### ISSUE THREAD

**Issue by eliskin** [gw-sd-2016/ClassExtractor#2]
@cctoombs @twood02

This week I worked on and fixed a ton of [TODO]s, which optimized a lot of the code (by removing duplicate functionality, as well as simplifying some algorithms). For instance, there is now only one conversion function and only one taskFinished function (ba1b01c36cb29f7fdcc39d0f1747b206065f2d9c and 2d0ca62d90510f149613d83786ee6dacdc6b672c); the flow of program logic is much simpler now. I also tested and optimized the frequency functions, simplifying the code in the process (a63dd3b70c48bfc807af6533ddb071e80fcc50cb and 9ed3d376da730f2e386c68970ebaeb549733d27a). Another thing I did was increase the ease at which some code can be debugged, by doing what Chris talked about in class such as evaluating `NSNotFound != compTextRange.location` instead of `compTextRange.location != NSNotFound` (0506760292d7fb5df8bacdc12231762ab16cd086).

I also got the Aylien API working. I tried many times in many different ways to get the API working using the Java API they provided, but the issue was that there was no easy way for Class Extractor to give Aylien a piece of text, and no easy way for Aylien to give back the concepts. Other solutions, such as Google's J2ObjC, which translates Java code to Objective-C code, weren't working properly. I finally figured out how to do it; I'm using Mashape's CURL API to communicate with Aylien, and that seems to be working well (174d55a949d3c39dbf66f39e9151e8d406165698).

All associated commits (oldest first):
ba511ed372f21427dcde7bfceecb3c83cfff12c4
0ae7eb31c896c57388ea8860a866d80deaaa5f20
d9e5c434cbcf5a02a754315b7854fe6123e0738e
d6ffaf50784bc62fc4212048ed21103e32d8f0ca
2e95f224704c505b97608bba471dfc6bad629fb1
ae91b53df11e890832f1347272af348d28a718c1
f0c90a4f1404978458237b813addfb4a4a762cea
c3a52a79d811d71cc9bfaf43c4affa3bc89e5a0a
2e6afddef60d6da43e0d72bcbc5947384f534124
6e1848074fcc09822d427d680fbb138096c86658
44a6665f9a464f2e8d75d1f2f497b6ca6edf00b8
ba1b01c36cb29f7fdcc39d0f1747b206065f2d9c
2d0ca62d90510f149613d83786ee6dacdc6b672c
5a6dd78b0819273a50653ce16d0f0c46fcc1c317
a63dd3b70c48bfc807af6533ddb071e80fcc50cb
9ed3d376da730f2e386c68970ebaeb549733d27a
0506760292d7fb5df8bacdc12231762ab16cd086
174d55a949d3c39dbf66f39e9151e8d406165698

**Comment by twood02** [comment]
sounds good. keep it up!
