### ISSUE TITLE
Week 13: NSURLSession and Word Cloud

### ISSUE THREAD

**Issue by eliskin** [gw-sd-2016/ClassExtractor#3]
@cctoombs @twood02 

This week I figured out how to use NSURLSession for executing a CURL command (1a9ee250c9955324c713d93ede977a4b0b05eabf), which is much faster and much cleaner than using NSTask. I also made it so MP3s can now be used directly (instead of having to convert them to a wav first). The issue was that I couldn't get an AVAssetTrack from an mp3, but I don't actually need an AVAssetTrack with the way I'm currently chopping up the file (the AVAssetTrack code was leftover from an old way of converting, and since there was a nil check, MP3s always caused the function to return prematurely) (cc9ab74f6d11463435bdb7d59a6d98c29d50507d).

The other big thing I did this week was creating the word cloud view (219d03fa6f665f695e8a219ddbf0bc6766d2f2de, 40d79d423e5dfcbd259cf90941a9641395e90cb2, 84c5280263e7811508fdbfa8e5d0e38a04678f2b). Drawing the view, displaying the name of the view's represented topic, displaying the time range of the represented topic, as well as calculating the size of the cloud based on the importance of its represented topic is implemented. I included some sample test code to draw one cloud with some sample input.

All associated commits (oldest first):
1a9ee250c9955324c713d93ede977a4b0b05eabf
cc9ab74f6d11463435bdb7d59a6d98c29d50507d
c62ffcb0d43c35b0622dac4451ffb7a3d7941e61
29bcbcd2396e5a0bfe86902442d4535d2fd38d28
219d03fa6f665f695e8a219ddbf0bc6766d2f2de
40d79d423e5dfcbd259cf90941a9641395e90cb2
84c5280263e7811508fdbfa8e5d0e38a04678f2b

**Comment by twood02** [comment]
sounds good!  Looking forward to seeing a sample cloud on Tuesday
